# Generated by Django 3.1.2 on 2020-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mdata',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
