# -*- coding: utf-8 -*-
"""word_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DHqWJrMsFHnKEK7crZlQV8cuG5wG6Ugq
"""

import pandas as pd
import numpy as np
import spacy
import csv
from spacy import displacy
from spacy.util import minibatch, compounding
import matplotlib.pyplot as plt
# from django.contrib.staticfiles.storage import staticfiles_storage

def predict(txt):
  '''PUT THE SPACY WEIGHT FOLDER'''
  print("Word Classifier Started")
  # nlp2 = spacy.load(staticfiles_storage.path('/spacy_model'))
  nlp2 = spcay.load('spcay_model')
  doc2 = nlp2(txt)
  if(doc2.cats['SCORE']>0.5):
    print("Word Classification Ended")
    return True
  else:
   return False

a = pd.read_csv('new_1.csv', encoding = "latin1")

for row in a['']:
    print(row)

def update_data(filt_equi_path, filt_state_path, equi_path, state_path, no_days):
    df = pd.read_csv("equi.csv")
    df = df.drop(['Unnamed: 0'], axis=1)
    equi_list = df.values.tolist()
    df2 = pd.read_csv("state.csv")
    df2 = df2.drop(['Unnamed: 0'], axis=1)
    state_list = df.values.tolist()
    with open(filt_state_path, 'a+', newline='') as file:
        writer = csv.writer(file)
        for i in range(no_days):
            writer.writerow(state_list[i])
    with open(filt_equi_path, 'a+', newline='') as file:
        writer = csv.writer(file)
        for i in range(no_days):
            writer.writerow(equi_list[i])
            
df = pd.read_csv('scrapped_backup.csv')
len(df.index)